version: '3.3'

services:
  church-service:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    # Where the data will be persisted if you are using the container please change this to your local path
    volumes:
      - my-db:/var/lib/mysql # C:\Users\prince

volumes:
  my-db: